; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=RV32I
; RUN: llc -mtriple=riscv32 -mattr=+xandesperf \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=RV32IXANDES
; RUN: llc -mtriple=riscv64 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=RV64I
; RUN: llc -mtriple=riscv64 -mattr=+xandesperf \
; RUN:   -verify-machineinstrs < %s | FileCheck %s -check-prefix=RV64IXANDES

declare void @abort()

define void @bbc(i32 %a) nounwind {
; RV32I-LABEL: bbc:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 15
; RV32I-NEXT:    bgez a0, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %end
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB0_2: # %abort
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    call abort@plt
;
; RV32IXANDES-LABEL: bbc:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bbc a0, 16, .LBB0_2
; RV32IXANDES-NEXT:  # %bb.1: # %end
; RV32IXANDES-NEXT:    ret
; RV32IXANDES-NEXT:  .LBB0_2: # %abort
; RV32IXANDES-NEXT:    addi sp, sp, -16
; RV32IXANDES-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IXANDES-NEXT:    call abort@plt
;
; RV64I-LABEL: bbc:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 47
; RV64I-NEXT:    bgez a0, .LBB0_2
; RV64I-NEXT:  # %bb.1: # %end
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB0_2: # %abort
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call abort@plt
;
; RV64IXANDES-LABEL: bbc:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bbc a0, 16, .LBB0_2
; RV64IXANDES-NEXT:  # %bb.1: # %end
; RV64IXANDES-NEXT:    ret
; RV64IXANDES-NEXT:  .LBB0_2: # %abort
; RV64IXANDES-NEXT:    addi sp, sp, -16
; RV64IXANDES-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IXANDES-NEXT:    call abort@plt
  %mask = shl i32 1, 16
  %and = and i32 %a, %mask
  %tst = icmp eq i32 %and, 0
  br i1 %tst, label %abort, label %end
end:
  ret void
abort:
  tail call void @abort()
  unreachable
}

define void @bbs(i32 %a) nounwind {
; RV32I-LABEL: bbs:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    bltz a0, .LBB1_2
; RV32I-NEXT:  # %bb.1: # %end
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB1_2: # %abort
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    call abort@plt
;
; RV32IXANDES-LABEL: bbs:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bbs a0, 23, .LBB1_2
; RV32IXANDES-NEXT:  # %bb.1: # %end
; RV32IXANDES-NEXT:    ret
; RV32IXANDES-NEXT:  .LBB1_2: # %abort
; RV32IXANDES-NEXT:    addi sp, sp, -16
; RV32IXANDES-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IXANDES-NEXT:    call abort@plt
;
; RV64I-LABEL: bbs:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 40
; RV64I-NEXT:    bltz a0, .LBB1_2
; RV64I-NEXT:  # %bb.1: # %end
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB1_2: # %abort
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call abort@plt
;
; RV64IXANDES-LABEL: bbs:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bbs a0, 23, .LBB1_2
; RV64IXANDES-NEXT:  # %bb.1: # %end
; RV64IXANDES-NEXT:    ret
; RV64IXANDES-NEXT:  .LBB1_2: # %abort
; RV64IXANDES-NEXT:    addi sp, sp, -16
; RV64IXANDES-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IXANDES-NEXT:    call abort@plt
  %mask = shl i32 1, 23
  %and = and i32 %a, %mask
  %tst = icmp ne i32 %and, 0
  br i1 %tst, label %abort, label %end
end:
  ret void
abort:
  tail call void @abort()
  unreachable
}

define void @beqc(i32 %a) nounwind {
; RV32I-LABEL: beqc:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a1, 5
; RV32I-NEXT:    beq a0, a1, .LBB2_2
; RV32I-NEXT:  # %bb.1: # %end
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB2_2: # %abort
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    call abort@plt
;
; RV32IXANDES-LABEL: beqc:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    beqc a0, 5, .LBB2_2
; RV32IXANDES-NEXT:  # %bb.1: # %end
; RV32IXANDES-NEXT:    ret
; RV32IXANDES-NEXT:  .LBB2_2: # %abort
; RV32IXANDES-NEXT:    addi sp, sp, -16
; RV32IXANDES-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IXANDES-NEXT:    call abort@plt
;
; RV64I-LABEL: beqc:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    li a1, 5
; RV64I-NEXT:    beq a0, a1, .LBB2_2
; RV64I-NEXT:  # %bb.1: # %end
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB2_2: # %abort
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call abort@plt
;
; RV64IXANDES-LABEL: beqc:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    beqc a0, 5, .LBB2_2
; RV64IXANDES-NEXT:  # %bb.1: # %end
; RV64IXANDES-NEXT:    ret
; RV64IXANDES-NEXT:  .LBB2_2: # %abort
; RV64IXANDES-NEXT:    addi sp, sp, -16
; RV64IXANDES-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IXANDES-NEXT:    call abort@plt
  %tst = icmp eq i32 %a, 5
  br i1 %tst, label %abort, label %end
end:
  ret void
abort:
  tail call void @abort()
  unreachable
}

define void @bnec(i32 %a) nounwind {
; RV32I-LABEL: bnec:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a1, 27
; RV32I-NEXT:    bne a0, a1, .LBB3_2
; RV32I-NEXT:  # %bb.1: # %end
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB3_2: # %abort
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    call abort@plt
;
; RV32IXANDES-LABEL: bnec:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bnec a0, 27, .LBB3_2
; RV32IXANDES-NEXT:  # %bb.1: # %end
; RV32IXANDES-NEXT:    ret
; RV32IXANDES-NEXT:  .LBB3_2: # %abort
; RV32IXANDES-NEXT:    addi sp, sp, -16
; RV32IXANDES-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; RV32IXANDES-NEXT:    call abort@plt
;
; RV64I-LABEL: bnec:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    li a1, 27
; RV64I-NEXT:    bne a0, a1, .LBB3_2
; RV64I-NEXT:  # %bb.1: # %end
; RV64I-NEXT:    ret
; RV64I-NEXT:  .LBB3_2: # %abort
; RV64I-NEXT:    addi sp, sp, -16
; RV64I-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    call abort@plt
;
; RV64IXANDES-LABEL: bnec:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    bnec a0, 27, .LBB3_2
; RV64IXANDES-NEXT:  # %bb.1: # %end
; RV64IXANDES-NEXT:    ret
; RV64IXANDES-NEXT:  .LBB3_2: # %abort
; RV64IXANDES-NEXT:    addi sp, sp, -16
; RV64IXANDES-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; RV64IXANDES-NEXT:    call abort@plt
  %tst = icmp ne i32 %a, 27
  br i1 %tst, label %abort, label %end
end:
  ret void
abort:
  tail call void @abort()
  unreachable
}

define i8 @sext_i1_to_i8(i1 %a) {
; RV32I-LABEL: sext_i1_to_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i1_to_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i1_to_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i1_to_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i1 %a to i8
  ret i8 %1
}

define i16 @sext_i1_to_i16(i1 %a) {
; RV32I-LABEL: sext_i1_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i1_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i1_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i1_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i1 %a to i16
  ret i16 %1
}

define i32 @sext_i1_to_i32(i1 %a) {
; RV32I-LABEL: sext_i1_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i1_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i1_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i1_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i1 %a to i32
  ret i32 %1
}

define i64 @sext_i1_to_i64(i1 %a) {
; RV32I-LABEL: sext_i1_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    mv a1, a0
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i1_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    mv a1, a0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i1_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i1_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i1 %a to i64
  ret i64 %1
}

define i16 @sext_i8_to_i16(i8 %a) {
; RV32I-LABEL: sext_i8_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i8_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i8_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i8_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i8 %a to i16
  ret i16 %1
}

define i32 @sext_i8_to_i32(i8 %a) {
; RV32I-LABEL: sext_i8_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i8_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i8_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i8_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i8 %a to i32
  ret i32 %1
}

define i64 @sext_i8_to_i64(i8 %a) {
; RV32I-LABEL: sext_i8_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a0, 24
; RV32I-NEXT:    srai a0, a1, 24
; RV32I-NEXT:    srai a1, a1, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i8_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a2, a0, 7, 0
; RV32IXANDES-NEXT:    bfos a1, a0, 7, 7
; RV32IXANDES-NEXT:    mv a0, a2
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i8_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i8_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i8 %a to i64
  ret i64 %1
}

define i32 @sext_i16_to_i32(i16 %a) {
; RV32I-LABEL: sext_i16_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 16
; RV32I-NEXT:    srai a0, a0, 16
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i16_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i16_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i16_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i16 %a to i32
  ret i32 %1
}

define i64 @sext_i16_to_i64(i16 %a) {
; RV32I-LABEL: sext_i16_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a0, 16
; RV32I-NEXT:    srai a0, a1, 16
; RV32I-NEXT:    srai a1, a1, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i16_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a2, a0, 15, 0
; RV32IXANDES-NEXT:    bfos a1, a0, 15, 15
; RV32IXANDES-NEXT:    mv a0, a2
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i16_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i16_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = sext i16 %a to i64
  ret i64 %1
}

define i64 @sext_i32_to_i64(i32 %a) {
; RV32I-LABEL: sext_i32_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    srai a1, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: sext_i32_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    srai a1, a0, 31
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: sext_i32_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: sext_i32_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    ret
  %1 = sext i32 %a to i64
  ret i64 %1
}

define i8 @zext_i1_to_i8(i1 %a) {
; RV32I-LABEL: zext_i1_to_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i1_to_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i1_to_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i1_to_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 1
; RV64IXANDES-NEXT:    ret
  %1 = zext i1 %a to i8
  ret i8 %1
}

define i16 @zext_i1_to_i16(i1 %a) {
; RV32I-LABEL: zext_i1_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i1_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i1_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i1_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 1
; RV64IXANDES-NEXT:    ret
  %1 = zext i1 %a to i16
  ret i16 %1
}

define i32 @zext_i1_to_i32(i1 %a) {
; RV32I-LABEL: zext_i1_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i1_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i1_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i1_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 1
; RV64IXANDES-NEXT:    ret
  %1 = zext i1 %a to i32
  ret i32 %1
}

define i64 @zext_i1_to_i64(i1 %a) {
; RV32I-LABEL: zext_i1_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 1
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i1_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 1
; RV32IXANDES-NEXT:    li a1, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i1_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i1_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 1
; RV64IXANDES-NEXT:    ret
  %1 = zext i1 %a to i64
  ret i64 %1
}

define i16 @zext_i8_to_i16(i8 %a) {
; RV32I-LABEL: zext_i8_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 255
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i8_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 255
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i8_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 255
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i8_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 255
; RV64IXANDES-NEXT:    ret
  %1 = zext i8 %a to i16
  ret i16 %1
}

define i32 @zext_i8_to_i32(i8 %a) {
; RV32I-LABEL: zext_i8_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 255
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i8_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 255
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i8_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 255
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i8_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 255
; RV64IXANDES-NEXT:    ret
  %1 = zext i8 %a to i32
  ret i32 %1
}

define i64 @zext_i8_to_i64(i8 %a) {
; RV32I-LABEL: zext_i8_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a0, a0, 255
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i8_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    andi a0, a0, 255
; RV32IXANDES-NEXT:    li a1, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i8_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a0, a0, 255
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i8_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    andi a0, a0, 255
; RV64IXANDES-NEXT:    ret
  %1 = zext i8 %a to i64
  ret i64 %1
}

define i32 @zext_i16_to_i32(i16 %a) {
; RV32I-LABEL: zext_i16_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 16
; RV32I-NEXT:    srli a0, a0, 16
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i16_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfoz a0, a0, 15, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i16_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i16_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = zext i16 %a to i32
  ret i32 %1
}

define i64 @zext_i16_to_i64(i16 %a) {
; RV32I-LABEL: zext_i16_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 16
; RV32I-NEXT:    srli a0, a0, 16
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i16_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfoz a0, a0, 15, 0
; RV32IXANDES-NEXT:    li a1, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i16_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srli a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i16_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = zext i16 %a to i64
  ret i64 %1
}

define i64 @zext_i32_to_i64(i32 %a) {
; RV32I-LABEL: zext_i32_to_i64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a1, 0
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: zext_i32_to_i64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    li a1, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: zext_i32_to_i64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 32
; RV64I-NEXT:    srli a0, a0, 32
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: zext_i32_to_i64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a0, a0, 31, 0
; RV64IXANDES-NEXT:    ret
  %1 = zext i32 %a to i64
  ret i64 %1
}

define i1 @trunc_i8_to_i1(i8 %a) {
; RV32I-LABEL: trunc_i8_to_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i8_to_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i8_to_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i8_to_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i8 %a to i1
  ret i1 %1
}

define i1 @trunc_i16_to_i1(i16 %a) {
; RV32I-LABEL: trunc_i16_to_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i16_to_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i16_to_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i16_to_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i16 %a to i1
  ret i1 %1
}

define i1 @trunc_i32_to_i1(i32 %a) {
; RV32I-LABEL: trunc_i32_to_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i1
  ret i1 %1
}

define i1 @trunc_i64_to_i1(i64 %a) {
; RV32I-LABEL: trunc_i64_to_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i1
  ret i1 %1
}

define i8 @trunc_i16_to_i8(i16 %a) {
; RV32I-LABEL: trunc_i16_to_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i16_to_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i16_to_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i16_to_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i16 %a to i8
  ret i8 %1
}

define i8 @trunc_i32_to_i8(i32 %a) {
; RV32I-LABEL: trunc_i32_to_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i8
  ret i8 %1
}

define i8 @trunc_i64_to_i8(i64 %a) {
; RV32I-LABEL: trunc_i64_to_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i8
  ret i8 %1
}

define i16 @trunc_i32_to_i16(i32 %a) {
; RV32I-LABEL: trunc_i32_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i16
  ret i16 %1
}

define i16 @trunc_i64_to_i16(i64 %a) {
; RV32I-LABEL: trunc_i64_to_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i16
  ret i16 %1
}

define i32 @trunc_i64_to_i32(i64 %a) {
; RV32I-LABEL: trunc_i64_to_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i32
  ret i32 %1
}

define signext i1 @trunc_i8_to_sext_i1(i8 %a) {
; RV32I-LABEL: trunc_i8_to_sext_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i8_to_sext_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i8_to_sext_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i8_to_sext_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i8 %a to i1
  ret i1 %1
}

define signext i1 @trunc_i16_to_sext_i1(i16 %a) {
; RV32I-LABEL: trunc_i16_to_sext_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i16_to_sext_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i16_to_sext_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i16_to_sext_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i16 %a to i1
  ret i1 %1
}

define signext i1 @trunc_i32_to_sext_i1(i32 %a) {
; RV32I-LABEL: trunc_i32_to_sext_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_sext_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_sext_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_sext_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i1
  ret i1 %1
}

define signext i1 @trunc_i64_to_sext_i1(i64 %a) {
; RV32I-LABEL: trunc_i64_to_sext_i1:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 31
; RV32I-NEXT:    srai a0, a0, 31
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_sext_i1:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_sext_i1:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 63
; RV64I-NEXT:    srai a0, a0, 63
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_sext_i1:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 0, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i1
  ret i1 %1
}

define signext i8 @trunc_i16_to_sext_i8(i16 %a) {
; RV32I-LABEL: trunc_i16_to_sext_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i16_to_sext_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i16_to_sext_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i16_to_sext_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i16 %a to i8
  ret i8 %1
}

define signext i8 @trunc_i32_to_sext_i8(i32 %a) {
; RV32I-LABEL: trunc_i32_to_sext_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_sext_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_sext_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_sext_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i8
  ret i8 %1
}

define signext i8 @trunc_i64_to_sext_i8(i64 %a) {
; RV32I-LABEL: trunc_i64_to_sext_i8:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_sext_i8:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_sext_i8:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 56
; RV64I-NEXT:    srai a0, a0, 56
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_sext_i8:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 7, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i8
  ret i8 %1
}

define signext i16 @trunc_i32_to_sext_i16(i32 %a) {
; RV32I-LABEL: trunc_i32_to_sext_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 16
; RV32I-NEXT:    srai a0, a0, 16
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i32_to_sext_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i32_to_sext_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i32_to_sext_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i32 %a to i16
  ret i16 %1
}

define signext i16 @trunc_i64_to_sext_i16(i64 %a) {
; RV32I-LABEL: trunc_i64_to_sext_i16:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a0, a0, 16
; RV32I-NEXT:    srai a0, a0, 16
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_sext_i16:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_sext_i16:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 48
; RV64I-NEXT:    srai a0, a0, 48
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_sext_i16:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a0, a0, 15, 0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i16
  ret i16 %1
}

define signext i32 @trunc_i64_to_sext_i32(i64 %a) {
; RV32I-LABEL: trunc_i64_to_sext_i32:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: trunc_i64_to_sext_i32:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: trunc_i64_to_sext_i32:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a0, a0
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: trunc_i64_to_sext_i32:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    ret
  %1 = trunc i64 %a to i32
  ret i32 %1
}

@var32 = global i32 0

define void @bfoz_from_and(i32 %fields) {
; RV32I-LABEL: bfoz_from_and:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a0, 6
; RV32I-NEXT:    srli a1, a1, 29
; RV32I-NEXT:    lui a2, %hi(var32)
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    slli a1, a0, 31
; RV32I-NEXT:    slli a0, a0, 20
; RV32I-NEXT:    srli a1, a1, 16
; RV32I-NEXT:    srli a0, a0, 8
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    sw a0, %lo(var32)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfoz_from_and:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfoz a1, a0, 25, 23
; RV32IXANDES-NEXT:    lui a2, %hi(var32)
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    slli a1, a0, 15
; RV32IXANDES-NEXT:    bfoz a1, a1, 15, 0
; RV32IXANDES-NEXT:    bfoz a0, a0, 12, 23
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    sw a0, %lo(var32)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfoz_from_and:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 38
; RV64I-NEXT:    srli a1, a1, 61
; RV64I-NEXT:  .Lpcrel_hi0:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64I-NEXT:    slli a1, a0, 63
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a1, a1, 48
; RV64I-NEXT:    srli a0, a0, 40
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64I-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfoz_from_and:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a1, a0, 25, 23
; RV64IXANDES-NEXT:  .Lpcrel_hi0:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64IXANDES-NEXT:    slli a1, a0, 15
; RV64IXANDES-NEXT:    bfoz a1, a1, 15, 0
; RV64IXANDES-NEXT:    bfoz a0, a0, 12, 23
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64IXANDES-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi0)(a2)
; RV64IXANDES-NEXT:    ret

; MSB >= LSB
  %shifted1 = lshr i32 %fields, 23
  %masked1 = and i32 %shifted1, 7
  store volatile i32 %masked1, i32* @var32

; MSB = 0
  %shifted2 = shl i32 %fields, 15
  %masked2 = and i32 %shifted2, 32768
  store volatile i32 %masked2, i32* @var32

; LSB > MSB
  %shifted3 = shl i32 %fields, 12
  %masked3 = and i32 %shifted3, 16773120
  store volatile i32 %masked3, i32* @var32

  ret void
}

define void @bfoz_from_srl(i32 %fields) {
; RV32I-LABEL: bfoz_from_srl:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a0, 31
; RV32I-NEXT:    srli a1, a1, 13
; RV32I-NEXT:    lui a2, %hi(var32)
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    slli a1, a0, 26
; RV32I-NEXT:    srli a1, a1, 7
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    slli a1, a0, 9
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    srli a1, a1, 19
; RV32I-NEXT:    srli a0, a0, 20
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    sw a0, %lo(var32)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfoz_from_srl:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfoz a1, a0, 0, 18
; RV32IXANDES-NEXT:    lui a2, %hi(var32)
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    bfoz a1, a0, 19, 24
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    bfoz a1, a0, 22, 10
; RV32IXANDES-NEXT:    bfoz a0, a0, 23, 12
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    sw a0, %lo(var32)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfoz_from_srl:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 63
; RV64I-NEXT:    srli a1, a1, 45
; RV64I-NEXT:  .Lpcrel_hi1:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64I-NEXT:    slli a1, a0, 58
; RV64I-NEXT:    srli a1, a1, 39
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64I-NEXT:    slli a1, a0, 41
; RV64I-NEXT:    slli a0, a0, 40
; RV64I-NEXT:    srli a1, a1, 51
; RV64I-NEXT:    srli a0, a0, 52
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64I-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfoz_from_srl:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a1, a0, 0, 18
; RV64IXANDES-NEXT:  .Lpcrel_hi1:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64IXANDES-NEXT:    bfoz a1, a0, 19, 24
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64IXANDES-NEXT:    bfoz a1, a0, 22, 10
; RV64IXANDES-NEXT:    bfoz a0, a0, 23, 12
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64IXANDES-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi1)(a2)
; RV64IXANDES-NEXT:    ret

; MSB = 0
  %shl1 = shl i32 %fields, 31
  %srl1 = lshr i32 %shl1, 13
  store volatile i32 %srl1, i32* @var32

; MSB < LSB
  %shl2 = shl i32 %fields, 26
  %srl2 = lshr i32 %shl2, 7
  store volatile i32 %srl2, i32* @var32

; MSB >= LSB
  %shl3 = shl i32 %fields, 9
  %srl3 = lshr i32 %shl3, 19
  store volatile i32 %srl3, i32* @var32

  %and = and i32 %fields, 16773120
  %srl = lshr i32 %and, 12
  store volatile i32 %srl, i32* @var32

  ret void
}

define void @bfos_from_sra(i32 %fields) {
; RV32I-LABEL: bfos_from_sra:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a0, 31
; RV32I-NEXT:    srai a1, a1, 17
; RV32I-NEXT:    lui a2, %hi(var32)
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    slli a1, a0, 29
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    srai a1, a1, 11
; RV32I-NEXT:    srai a0, a0, 24
; RV32I-NEXT:    sw a1, %lo(var32)(a2)
; RV32I-NEXT:    sw a0, %lo(var32)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfos_from_sra:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bfos a1, a0, 0, 14
; RV32IXANDES-NEXT:    lui a2, %hi(var32)
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    bfos a1, a0, 18, 20
; RV32IXANDES-NEXT:    bfos a0, a0, 23, 16
; RV32IXANDES-NEXT:    sw a1, %lo(var32)(a2)
; RV32IXANDES-NEXT:    sw a0, %lo(var32)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfos_from_sra:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 31
; RV64I-NEXT:    sraiw a1, a1, 17
; RV64I-NEXT:  .Lpcrel_hi2:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64I-NEXT:    slli a1, a0, 29
; RV64I-NEXT:    slli a0, a0, 8
; RV64I-NEXT:    sraiw a1, a1, 11
; RV64I-NEXT:    sraiw a0, a0, 24
; RV64I-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64I-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfos_from_sra:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a1, a0, 0, 14
; RV64IXANDES-NEXT:  .Lpcrel_hi2:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var32)
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64IXANDES-NEXT:    bfos a1, a0, 18, 20
; RV64IXANDES-NEXT:    bfos a0, a0, 23, 16
; RV64IXANDES-NEXT:    sw a1, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64IXANDES-NEXT:    sw a0, %pcrel_lo(.Lpcrel_hi2)(a2)
; RV64IXANDES-NEXT:    ret

; MSB = 0
  %shl1 = shl i32 %fields, 31
  %sra1 = ashr i32 %shl1, 17
  store volatile i32 %sra1, i32* @var32

; MSB < LSB
  %shl2 = shl i32 %fields, 29
  %sra2 = ashr i32 %shl2, 11
  store volatile i32 %sra2, i32* @var32

; MSB >= LSB
  %shl3 = shl i32 %fields, 8
  %srl3 = ashr i32 %shl3, 24
  store volatile i32 %srl3, i32* @var32

  ret void
}

@var64 = global i64 0

define void @bfoz_from_and64(i64 %fields) {
; RV32I-LABEL: bfoz_from_and64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a1, 6
; RV32I-NEXT:    lui a2, %hi(var64)
; RV32I-NEXT:    srli a1, a1, 20
; RV32I-NEXT:    sw zero, %lo(var64+4)(a2)
; RV32I-NEXT:    sw a1, %lo(var64)(a2)
; RV32I-NEXT:    slli a1, a0, 31
; RV32I-NEXT:    srli a1, a1, 15
; RV32I-NEXT:    sw a1, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a1, a0, 20
; RV32I-NEXT:    srli a1, a1, 28
; RV32I-NEXT:    slli a0, a0, 24
; RV32I-NEXT:    sw zero, %lo(var64)(a2)
; RV32I-NEXT:    sw a1, %lo(var64+4)(a2)
; RV32I-NEXT:    sw a0, %lo(var64)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfoz_from_and64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lui a2, %hi(var64)
; RV32IXANDES-NEXT:    bfoz a1, a1, 25, 14
; RV32IXANDES-NEXT:    sw zero, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    sw a1, %lo(var64)(a2)
; RV32IXANDES-NEXT:    bfoz a1, a0, 0, 16
; RV32IXANDES-NEXT:    sw a1, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    bfoz a1, a0, 11, 8
; RV32IXANDES-NEXT:    slli a0, a0, 24
; RV32IXANDES-NEXT:    sw zero, %lo(var64)(a2)
; RV32IXANDES-NEXT:    sw a1, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    sw a0, %lo(var64)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfoz_from_and64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 6
; RV64I-NEXT:    srli a1, a1, 52
; RV64I-NEXT:  .Lpcrel_hi3:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64I-NEXT:    slli a1, a0, 63
; RV64I-NEXT:    slli a0, a0, 52
; RV64I-NEXT:    srli a1, a1, 15
; RV64I-NEXT:    srli a0, a0, 28
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64I-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfoz_from_and64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a1, a0, 57, 46
; RV64IXANDES-NEXT:  .Lpcrel_hi3:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64IXANDES-NEXT:    bfoz a1, a0, 0, 48
; RV64IXANDES-NEXT:    bfoz a0, a0, 24, 35
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64IXANDES-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi3)(a2)
; RV64IXANDES-NEXT:    ret

; MSB >= LSB
  %shifted1 = lshr i64 %fields, 46
  %masked1 = and i64 %shifted1, 4095
  store volatile i64 %masked1, i64* @var64

; MSB = 0
  %shifted2 = shl i64 %fields, 48
  %masked2 = and i64 %shifted2, 281474976710656
  store volatile i64 %masked2, i64* @var64

; LSB > MSB
  %shifted3 = shl i64 %fields, 24
  %masked3 = and i64 %shifted3, 68702699520
  store volatile i64 %masked3, i64* @var64

  ret void
}

define void @bfoz_from_srl64(i64 %fields) {
; RV32I-LABEL: bfoz_from_srl64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a3, a0, 31
; RV32I-NEXT:    lui a2, %hi(var64)
; RV32I-NEXT:    srli a3, a3, 19
; RV32I-NEXT:    sw zero, %lo(var64)(a2)
; RV32I-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a3, a0, 19
; RV32I-NEXT:    sw a3, %lo(var64)(a2)
; RV32I-NEXT:    srli a3, a0, 13
; RV32I-NEXT:    slli a4, a1, 19
; RV32I-NEXT:    or a3, a4, a3
; RV32I-NEXT:    slli a3, a3, 7
; RV32I-NEXT:    srli a3, a3, 7
; RV32I-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a3, a1, 9
; RV32I-NEXT:    srli a3, a3, 19
; RV32I-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a3, a1, 22
; RV32I-NEXT:    andi a1, a1, 15
; RV32I-NEXT:    srli a4, a0, 10
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    slli a1, a1, 8
; RV32I-NEXT:    or a3, a4, a3
; RV32I-NEXT:    or a0, a0, a1
; RV32I-NEXT:    sw a3, %lo(var64)(a2)
; RV32I-NEXT:    sw zero, %lo(var64+4)(a2)
; RV32I-NEXT:    sw a0, %lo(var64)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfoz_from_srl64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lui a2, %hi(var64)
; RV32IXANDES-NEXT:    bfoz a3, a0, 0, 12
; RV32IXANDES-NEXT:    sw zero, %lo(var64)(a2)
; RV32IXANDES-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    slli a3, a0, 19
; RV32IXANDES-NEXT:    sw a3, %lo(var64)(a2)
; RV32IXANDES-NEXT:    srli a3, a0, 13
; RV32IXANDES-NEXT:    slli a4, a1, 19
; RV32IXANDES-NEXT:    or a3, a4, a3
; RV32IXANDES-NEXT:    bfoz a3, a3, 24, 0
; RV32IXANDES-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    bfoz a3, a1, 22, 10
; RV32IXANDES-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    slli a3, a1, 22
; RV32IXANDES-NEXT:    andi a1, a1, 15
; RV32IXANDES-NEXT:    srli a4, a0, 10
; RV32IXANDES-NEXT:    srli a0, a0, 24
; RV32IXANDES-NEXT:    slli a1, a1, 8
; RV32IXANDES-NEXT:    or a3, a4, a3
; RV32IXANDES-NEXT:    or a0, a0, a1
; RV32IXANDES-NEXT:    sw a3, %lo(var64)(a2)
; RV32IXANDES-NEXT:    sw zero, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    sw a0, %lo(var64)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfoz_from_srl64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 63
; RV64I-NEXT:    srli a1, a1, 19
; RV64I-NEXT:  .Lpcrel_hi4:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64I-NEXT:    slli a1, a0, 26
; RV64I-NEXT:    srli a1, a1, 7
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64I-NEXT:    slli a1, a0, 9
; RV64I-NEXT:    slli a0, a0, 28
; RV64I-NEXT:    srli a1, a1, 19
; RV64I-NEXT:    srli a0, a0, 52
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64I-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfoz_from_srl64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfoz a1, a0, 0, 44
; RV64IXANDES-NEXT:  .Lpcrel_hi4:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64IXANDES-NEXT:    bfoz a1, a0, 19, 56
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64IXANDES-NEXT:    bfoz a1, a0, 54, 10
; RV64IXANDES-NEXT:    bfoz a0, a0, 35, 24
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64IXANDES-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi4)(a2)
; RV64IXANDES-NEXT:    ret

; MSB = 0
  %shl1 = shl i64 %fields, 63
  %srl1 = lshr i64 %shl1, 19
  store volatile i64 %srl1, i64* @var64

; MSB < LSB
  %shl2 = shl i64 %fields, 26
  %srl2 = lshr i64 %shl2, 7
  store volatile i64 %srl2, i64* @var64

; MSB >= LSB
  %shl3 = shl i64 %fields, 9
  %srl3 = lshr i64 %shl3, 19
  store volatile i64 %srl3, i64* @var64

  %and = and i64 %fields, 68702699520
  %srl = lshr i64 %and, 24
  store volatile i64 %srl, i64* @var64

  ret void
}

define void @bfos_from_sra64(i64 %fields) {
; RV32I-LABEL: bfos_from_sra64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a3, a0, 31
; RV32I-NEXT:    lui a2, %hi(var64)
; RV32I-NEXT:    srai a3, a3, 17
; RV32I-NEXT:    sw zero, %lo(var64)(a2)
; RV32I-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a4, a1, 29
; RV32I-NEXT:    srli a3, a0, 3
; RV32I-NEXT:    or a4, a4, a3
; RV32I-NEXT:    srai a4, a4, 11
; RV32I-NEXT:    sw a4, %lo(var64+4)(a2)
; RV32I-NEXT:    slli a4, a0, 29
; RV32I-NEXT:    slli a3, a3, 21
; RV32I-NEXT:    srli a4, a4, 11
; RV32I-NEXT:    or a3, a4, a3
; RV32I-NEXT:    slli a1, a1, 8
; RV32I-NEXT:    sw a3, %lo(var64)(a2)
; RV32I-NEXT:    srai a3, a1, 24
; RV32I-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32I-NEXT:    srli a3, a0, 24
; RV32I-NEXT:    or a1, a1, a3
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    slli a1, a1, 8
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    or a0, a0, a1
; RV32I-NEXT:    sw a0, %lo(var64)(a2)
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: bfos_from_sra64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lui a2, %hi(var64)
; RV32IXANDES-NEXT:    bfos a3, a0, 0, 14
; RV32IXANDES-NEXT:    sw zero, %lo(var64)(a2)
; RV32IXANDES-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    srli a3, a0, 3
; RV32IXANDES-NEXT:    slli a4, a1, 29
; RV32IXANDES-NEXT:    or a4, a4, a3
; RV32IXANDES-NEXT:    srai a4, a4, 11
; RV32IXANDES-NEXT:    sw a4, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    bfoz a4, a0, 18, 20
; RV32IXANDES-NEXT:    slli a3, a3, 21
; RV32IXANDES-NEXT:    or a3, a4, a3
; RV32IXANDES-NEXT:    sw a3, %lo(var64)(a2)
; RV32IXANDES-NEXT:    bfos a3, a1, 23, 16
; RV32IXANDES-NEXT:    sw a3, %lo(var64+4)(a2)
; RV32IXANDES-NEXT:    srli a3, a0, 24
; RV32IXANDES-NEXT:    slli a1, a1, 8
; RV32IXANDES-NEXT:    or a1, a1, a3
; RV32IXANDES-NEXT:    slli a1, a1, 8
; RV32IXANDES-NEXT:    bfoz a0, a0, 23, 16
; RV32IXANDES-NEXT:    or a0, a0, a1
; RV32IXANDES-NEXT:    sw a0, %lo(var64)(a2)
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: bfos_from_sra64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a0, 63
; RV64I-NEXT:    srai a1, a1, 17
; RV64I-NEXT:  .Lpcrel_hi5:
; RV64I-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64I-NEXT:    slli a1, a0, 29
; RV64I-NEXT:    slli a0, a0, 8
; RV64I-NEXT:    srai a1, a1, 11
; RV64I-NEXT:    srai a0, a0, 24
; RV64I-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64I-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: bfos_from_sra64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bfos a1, a0, 0, 46
; RV64IXANDES-NEXT:  .Lpcrel_hi5:
; RV64IXANDES-NEXT:    auipc a2, %pcrel_hi(var64)
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64IXANDES-NEXT:    bfos a1, a0, 18, 52
; RV64IXANDES-NEXT:    bfos a0, a0, 55, 16
; RV64IXANDES-NEXT:    sd a1, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64IXANDES-NEXT:    sd a0, %pcrel_lo(.Lpcrel_hi5)(a2)
; RV64IXANDES-NEXT:    ret

; MSB = 0
  %shl1 = shl i64 %fields, 63
  %sra1 = ashr i64 %shl1, 17
  store volatile i64 %sra1, i64* @var64

; MSB < LSB
  %shl2 = shl i64 %fields, 29
  %sra2 = ashr i64 %shl2, 11
  store volatile i64 %sra2, i64* @var64

; MSB >= LSB
  %shl3 = shl i64 %fields, 8
  %srl3 = ashr i64 %shl3, 24
  store volatile i64 %srl3, i64* @var64

  ret void
}

define i32 @lea_h(i32 %a, i32 %b) nounwind {
; RV32I-LABEL: lea_h:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a1, 1
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_h:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.h a0, a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_h:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 1
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_h:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.h a0, a0, a1
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    ret
  %shl = shl i32 %b, 1
  %ret = add i32 %a, %shl
  ret i32 %ret
}

define i32 @lea_w(i32 %a, i32 %b) nounwind {
; RV32I-LABEL: lea_w:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a1, 2
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_w:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.w a0, a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_w:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 2
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_w:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.w a0, a0, a1
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    ret
  %shl = shl i32 %b, 2
  %ret = add i32 %a, %shl
  ret i32 %ret
}

define i32 @lea_d(i32 %a, i32 %b) nounwind {
; RV32I-LABEL: lea_d:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a1, a1, 3
; RV32I-NEXT:    add a0, a0, a1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_d:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.d a0, a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_d:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 3
; RV64I-NEXT:    addw a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_d:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.d a0, a0, a1
; RV64IXANDES-NEXT:    sext.w a0, a0
; RV64IXANDES-NEXT:    ret
  %shl = shl i32 %b, 3
  %ret = add i32 %a, %shl
  ret i32 %ret
}

define i64 @lea_h64(i64 %a, i64 %b) nounwind {
; RV32I-LABEL: lea_h64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a4, a2, 1
; RV32I-NEXT:    srli a2, a2, 31
; RV32I-NEXT:    slli a3, a3, 1
; RV32I-NEXT:    add a4, a0, a4
; RV32I-NEXT:    or a2, a3, a2
; RV32I-NEXT:    sltu a0, a4, a0
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    mv a0, a4
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_h64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.h a4, a0, a2
; RV32IXANDES-NEXT:    srli a2, a2, 31
; RV32IXANDES-NEXT:    slli a3, a3, 1
; RV32IXANDES-NEXT:    or a2, a3, a2
; RV32IXANDES-NEXT:    sltu a0, a4, a0
; RV32IXANDES-NEXT:    add a1, a1, a2
; RV32IXANDES-NEXT:    add a1, a1, a0
; RV32IXANDES-NEXT:    mv a0, a4
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_h64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 1
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_h64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.h a0, a0, a1
; RV64IXANDES-NEXT:    ret
  %shl = shl i64 %b, 1
  %ret = add i64 %a, %shl
  ret i64 %ret
}

define i64 @lea_w64(i64 %a, i64 %b) nounwind {
; RV32I-LABEL: lea_w64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a4, a2, 2
; RV32I-NEXT:    srli a2, a2, 30
; RV32I-NEXT:    slli a3, a3, 2
; RV32I-NEXT:    add a4, a0, a4
; RV32I-NEXT:    or a2, a3, a2
; RV32I-NEXT:    sltu a0, a4, a0
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    mv a0, a4
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_w64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.w a4, a0, a2
; RV32IXANDES-NEXT:    srli a2, a2, 30
; RV32IXANDES-NEXT:    slli a3, a3, 2
; RV32IXANDES-NEXT:    or a2, a3, a2
; RV32IXANDES-NEXT:    sltu a0, a4, a0
; RV32IXANDES-NEXT:    add a1, a1, a2
; RV32IXANDES-NEXT:    add a1, a1, a0
; RV32IXANDES-NEXT:    mv a0, a4
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_w64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_w64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.w a0, a0, a1
; RV64IXANDES-NEXT:    ret
  %shl = shl i64 %b, 2
  %ret = add i64 %a, %shl
  ret i64 %ret
}

define i64 @lea_d64(i64 %a, i64 %b) nounwind {
; RV32I-LABEL: lea_d64:
; RV32I:       # %bb.0:
; RV32I-NEXT:    slli a4, a2, 3
; RV32I-NEXT:    srli a2, a2, 29
; RV32I-NEXT:    slli a3, a3, 3
; RV32I-NEXT:    add a4, a0, a4
; RV32I-NEXT:    or a2, a3, a2
; RV32I-NEXT:    sltu a0, a4, a0
; RV32I-NEXT:    add a1, a1, a2
; RV32I-NEXT:    add a1, a1, a0
; RV32I-NEXT:    mv a0, a4
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: lea_d64:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    lea.d a4, a0, a2
; RV32IXANDES-NEXT:    srli a2, a2, 29
; RV32IXANDES-NEXT:    slli a3, a3, 3
; RV32IXANDES-NEXT:    or a2, a3, a2
; RV32IXANDES-NEXT:    sltu a0, a4, a0
; RV32IXANDES-NEXT:    add a1, a1, a2
; RV32IXANDES-NEXT:    add a1, a1, a0
; RV32IXANDES-NEXT:    mv a0, a4
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: lea_d64:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a1, a1, 3
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: lea_d64:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    lea.d a0, a0, a1
; RV64IXANDES-NEXT:    ret
  %shl = shl i64 %b, 3
  %ret = add i64 %a, %shl
  ret i64 %ret
}

define signext i32 @select_bbc(i32 signext %a, i32 signext %b, i32 signext %c) nounwind {
; RV32I-LABEL: select_bbc:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mv a3, a0
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    slli a3, a3, 15
; RV32I-NEXT:    bgez a3, .LBB56_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:  .LBB56_2:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: select_bbc:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bbc a0, 16, .LBB56_2
; RV32IXANDES-NEXT:  # %bb.1:
; RV32IXANDES-NEXT:    mv a1, a2
; RV32IXANDES-NEXT:  .LBB56_2:
; RV32IXANDES-NEXT:    mv a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: select_bbc:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mv a3, a0
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    slli a3, a3, 47
; RV64I-NEXT:    bgez a3, .LBB56_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:  .LBB56_2:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: select_bbc:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bbc a0, 16, .LBB56_2
; RV64IXANDES-NEXT:  # %bb.1:
; RV64IXANDES-NEXT:    mv a1, a2
; RV64IXANDES-NEXT:  .LBB56_2:
; RV64IXANDES-NEXT:    mv a0, a1
; RV64IXANDES-NEXT:    ret
  %mask = shl i32 1, 16
  %and = and i32 %a, %mask
  %tst = icmp eq i32 %and, 0
  %ret = select i1 %tst, i32 %b, i32 %c
  ret i32 %ret
}

define signext i32 @select_bbs(i32 signext %a, i32 signext %b, i32 signext %c) nounwind {
; RV32I-LABEL: select_bbs:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mv a3, a0
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    slli a3, a3, 15
; RV32I-NEXT:    bltz a3, .LBB57_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:  .LBB57_2:
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: select_bbs:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bbs a0, 16, .LBB57_2
; RV32IXANDES-NEXT:  # %bb.1:
; RV32IXANDES-NEXT:    mv a1, a2
; RV32IXANDES-NEXT:  .LBB57_2:
; RV32IXANDES-NEXT:    mv a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: select_bbs:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mv a3, a0
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    slli a3, a3, 47
; RV64I-NEXT:    bltz a3, .LBB57_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:  .LBB57_2:
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: select_bbs:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bbs a0, 16, .LBB57_2
; RV64IXANDES-NEXT:  # %bb.1:
; RV64IXANDES-NEXT:    mv a1, a2
; RV64IXANDES-NEXT:  .LBB57_2:
; RV64IXANDES-NEXT:    mv a0, a1
; RV64IXANDES-NEXT:    ret
  %mask = shl i32 1, 16
  %and = and i32 %a, %mask
  %tst = icmp ne i32 %and, 0
  %ret = select i1 %tst, i32 %b, i32 %c
  ret i32 %ret
}

define signext i32 @select_beqc(i32 signext %a, i32 signext %b, i32 signext %c) nounwind {
; RV32I-LABEL: select_beqc:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a3, 5
; RV32I-NEXT:    beq a0, a3, .LBB58_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a1, a2
; RV32I-NEXT:  .LBB58_2:
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: select_beqc:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    beqc a0, 5, .LBB58_2
; RV32IXANDES-NEXT:  # %bb.1:
; RV32IXANDES-NEXT:    mv a1, a2
; RV32IXANDES-NEXT:  .LBB58_2:
; RV32IXANDES-NEXT:    mv a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: select_beqc:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a3, 5
; RV64I-NEXT:    beq a0, a3, .LBB58_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a1, a2
; RV64I-NEXT:  .LBB58_2:
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: select_beqc:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    beqc a0, 5, .LBB58_2
; RV64IXANDES-NEXT:  # %bb.1:
; RV64IXANDES-NEXT:    mv a1, a2
; RV64IXANDES-NEXT:  .LBB58_2:
; RV64IXANDES-NEXT:    mv a0, a1
; RV64IXANDES-NEXT:    ret
  %tst = icmp eq i32 %a, 5
  %ret = select i1 %tst, i32 %b, i32 %c
  ret i32 %ret
}

define signext i32 @select_bnec(i32 signext %a, i32 signext %b, i32 signext %c) nounwind {
; RV32I-LABEL: select_bnec:
; RV32I:       # %bb.0:
; RV32I-NEXT:    li a3, 5
; RV32I-NEXT:    bne a0, a3, .LBB59_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a1, a2
; RV32I-NEXT:  .LBB59_2:
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: select_bnec:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    bnec a0, 5, .LBB59_2
; RV32IXANDES-NEXT:  # %bb.1:
; RV32IXANDES-NEXT:    mv a1, a2
; RV32IXANDES-NEXT:  .LBB59_2:
; RV32IXANDES-NEXT:    mv a0, a1
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: select_bnec:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a3, 5
; RV64I-NEXT:    bne a0, a3, .LBB59_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a1, a2
; RV64I-NEXT:  .LBB59_2:
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: select_bnec:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    bnec a0, 5, .LBB59_2
; RV64IXANDES-NEXT:  # %bb.1:
; RV64IXANDES-NEXT:    mv a1, a2
; RV64IXANDES-NEXT:  .LBB59_2:
; RV64IXANDES-NEXT:    mv a0, a1
; RV64IXANDES-NEXT:    ret
  %tst = icmp ne i32 %a, 5
  %ret = select i1 %tst, i32 %b, i32 %c
  ret i32 %ret
}

; Don't transfer AND+SRL to BFOZ if the mask of AND is exactly 0xffffffff.
define i32 @srliw_bfoz(i32 %a) {
; RV32I-LABEL: srliw_bfoz:
; RV32I:       # %bb.0:
; RV32I-NEXT:    srli a0, a0, 17
; RV32I-NEXT:    ret
;
; RV32IXANDES-LABEL: srliw_bfoz:
; RV32IXANDES:       # %bb.0:
; RV32IXANDES-NEXT:    srli a0, a0, 17
; RV32IXANDES-NEXT:    ret
;
; RV64I-LABEL: srliw_bfoz:
; RV64I:       # %bb.0:
; RV64I-NEXT:    srliw a0, a0, 17
; RV64I-NEXT:    ret
;
; RV64IXANDES-LABEL: srliw_bfoz:
; RV64IXANDES:       # %bb.0:
; RV64IXANDES-NEXT:    srliw a0, a0, 17
; RV64IXANDES-NEXT:    ret
 %ret = lshr i32 %a, 17
 ret i32 %ret
}
